export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Socket} from "@/app/socket"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
      <Socket></Socket></body>
    </html>
  )
}
